apiVersion: apps/v1
kind: Deployment

metadata:
  name: analytics-service
  namespace: disaster-response

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analytics-service

  template:
    metadata:
      labels:
        app: analytics-service

    spec:
      containers:
        - name: analytics-service
          image: disaster-response-network-analytics-service
          imagePullPolicy: Never

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/analytics_service

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: disaster-response-secrets
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: disaster-response-secrets
                  key: DB_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: SERVER_PORT
              value: "8082"