spring:
  application:
    name: disaster-response-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/disaster_response
    username: disaster_user
    password: disaster_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    secret: ${JWT_SECRET:VGhpcy1pcy1hLWRldmVsb3BtZW50LWtleS10aGF0LW11c3QtYmUtcmVwbGFjZWQtYmVmb3JlLXByb2R1Y3Rpb24=}
    expiration-ms: 3600000